"""Collect a sim2sim reference trace to TensorBoard for sim2real bring-up.

Runs the trained policy inside MuJoCo using exactly the same pipeline as
play_mujoco.py (it imports and reuses that module's state reading, controller and
policy), and logs, at every 100 Hz policy step, every quantity that matters for
sim2real comparison:

  * state/*       : the RAW physical states the lower machine sends up the serial
                    link (base ang vel, projected gravity, commands, virtual-leg
                    theta0/L0 and rates, wheel pos/vel) -- unscaled SI values.
  * action_raw/*  : the raw policy output (after clipping).
  * action_phys/* : the scaled physical command the NUC sends down (theta0_ref,
                    l0_ref, wheel_vel_ref), using the same action_scales/l0_offset
                    as the controller.

During early sim2real testing the live serial values can then be checked against
this known-good baseline in TensorBoard.

Each invocation writes to its own sub-run under --logdir, named with the date-time
and the command it was driven with (vx/wz/height) plus the duration, so multiple
traces stay distinguishable in the file system and in the TensorBoard run list
without having to open every one. Pass --run_name to override the auto name.

"""
import argparse
import datetime
import os
import sys

import numpy as np
from torch.utils.tensorboard import SummaryWriter

# Reuse play_mujoco.py wholesale (state reading helpers, constants, controller,
# policy) so this reference is generated by the very same code path it documents.
SCRIPTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "scripts")
sys.path.insert(0, os.path.abspath(SCRIPTS_DIR))
import mujoco
import controller as ctrl
import play_mujoco as pm

DEFAULT_LOGDIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reference_data")

# Per-leg names for the 6-dim action, in the downlink order.
ACTION_NAMES = ["L_theta", "L_l0", "L_wheel", "R_theta", "R_l0", "R_wheel"]


def parse_args():
    p = argparse.ArgumentParser(description="Collect sim2sim reference data to TensorBoard")
    p.add_argument("--seconds", type=float, default=30.0, help="trace duration [s]")
    p.add_argument("--vx", type=float, default=0.0, help="forward velocity command [m/s]")
    p.add_argument("--wz", type=float, default=0.0, help="yaw rate command [rad/s]")
    p.add_argument("--height", type=float, default=pm.default_command["height"], help="body height command [m]")
    p.add_argument("--device", default="cpu")
    p.add_argument("--logdir", default=DEFAULT_LOGDIR,
                   help="parent directory; each run is written to a named sub-folder under it")
    p.add_argument("--run_name", default=None,
                   help="override the auto-generated run sub-folder name")
    return p.parse_args()


def _fmt_command_value(value):
    """Format a command value for a run name: fixed 2 decimals, sign-safe, no dot.

    Keeps the name a valid single path segment (e.g. -0.50 -> "m0p50") so vx/wz/
    height stay readable and never introduce a path separator or a leading '-'
    that some tools mistake for a flag.
    """
    sign = "m" if value < 0 else ""
    return f"{sign}{abs(value):.2f}".replace(".", "p")


def build_run_name(args):
    """Build a self-describing run sub-folder name from the command and the date.

    Encodes everything needed to tell traces apart at a glance -- the date-time
    the trace was recorded, the vx/wz/height command it was driven with, and the
    duration -- e.g. Jun09_20-15-30_vx0p50_wz0p00_h0p18_t30s. --run_name wins if
    given.

    The date-time format (%b%d_%H-%M-%S) matches the training run naming under
    logs/ (see task_registry.py), keeping a single timestamp convention repo-wide.
    """
    if args.run_name:
        return args.run_name
    stamp = datetime.datetime.now().strftime("%b%d_%H-%M-%S")
    return (
        f"{stamp}"
        f"_vx{_fmt_command_value(args.vx)}"
        f"_wz{_fmt_command_value(args.wz)}"
        f"_h{_fmt_command_value(args.height)}"
        f"_t{args.seconds:g}s"
    )


def log_state(writer, step, base_ang_vel, projected_gravity, commands, legs, dof_vel, dof_pos):
    """Log the 21 raw physical state quantities (the sim2real uplink contents)."""
    left_wheel = ctrl.dof_indices["left_wheel"]
    right_wheel = ctrl.dof_indices["right_wheel"]
    scalars = {
        "state/base_ang_vel_x": base_ang_vel[0],
        "state/base_ang_vel_y": base_ang_vel[1],
        "state/base_ang_vel_z": base_ang_vel[2],
        "state/projected_gravity_x": projected_gravity[0],
        "state/projected_gravity_y": projected_gravity[1],
        "state/projected_gravity_z": projected_gravity[2],
        "state/command_vx": commands[0],
        "state/command_wz": commands[1],
        "state/command_height": commands[2],
        "state/theta0_L": legs["theta0"][0],
        "state/theta0_R": legs["theta0"][1],
        "state/theta0_dot_L": legs["theta0_dot"][0],
        "state/theta0_dot_R": legs["theta0_dot"][1],
        "state/L0_L": legs["L0"][0],
        "state/L0_R": legs["L0"][1],
        "state/L0_dot_L": legs["L0_dot"][0],
        "state/L0_dot_R": legs["L0_dot"][1],
        "state/wheel_pos_L": dof_pos[left_wheel],
        "state/wheel_pos_R": dof_pos[right_wheel],
        "state/wheel_vel_L": dof_vel[left_wheel],
        "state/wheel_vel_R": dof_vel[right_wheel],
    }
    for tag, value in scalars.items():
        writer.add_scalar(tag, float(value), step)


def log_actions(writer, step, action):
    """Log the raw policy action and the scaled physical command (downlink)."""
    # Raw policy output (already clipped by the caller).
    for i, name in enumerate(ACTION_NAMES):
        writer.add_scalar(f"action_raw/{name}", float(action[i]), step)

    # Physical command, identical scaling to controller.compute_torques / the
    # sim2real downlink: theta0_ref = a*theta; l0_ref = a*l0 + l0_offset;
    # wheel_vel_ref = a*vel.
    theta = ctrl.action_scales["theta"]
    l0 = ctrl.action_scales["l0"]
    vel = ctrl.action_scales["vel"]
    l0_offset = ctrl.control["l0_offset"]
    phys = {
        "action_phys/theta0_ref_L": action[0] * theta,
        "action_phys/l0_ref_L": action[1] * l0 + l0_offset,
        "action_phys/wheel_vel_ref_L": action[2] * vel,
        "action_phys/theta0_ref_R": action[3] * theta,
        "action_phys/l0_ref_R": action[4] * l0 + l0_offset,
        "action_phys/wheel_vel_ref_R": action[5] * vel,
    }
    for tag, value in phys.items():
        writer.add_scalar(tag, float(value), step)


def main():
    args = parse_args()

    # --- Set up MuJoCo + policy exactly like play_mujoco.main() ---
    model = mujoco.MjModel.from_xml_path(pm.MODEL_XML)
    model.opt.timestep = pm.control_timing["sim_dt"]
    data = mujoco.MjData(model)
    pm.reset_state(data)
    mujoco.mj_forward(model, data)

    policy = pm.SequencePolicy(pm.POLICY_PT, device=args.device)
    commands = np.array([args.vx, args.wz, args.height], dtype=np.float32)
    last_actions = np.zeros(pm.network["num_actions"], dtype=np.float32)

    # read_observation is nested inside play_mujoco.main(), so replicate it here
    # but also return the raw physical pieces we need to log.
    def read_state():
        quat = data.qpos[3:7]
        base_ang_vel = data.qvel[3:6].copy()
        projected_gravity = pm.quat_rotate_inverse_wxyz(quat, np.array([0.0, 0.0, -1.0]))
        dof_pos = data.qpos[pm.QPOS_JOINT_START:].copy()
        dof_vel = data.qvel[pm.QVEL_JOINT_START:].copy()
        legs = ctrl.leg_states(dof_pos, dof_vel)
        obs = ctrl.build_observation(
            base_ang_vel, projected_gravity, commands, legs, dof_pos, dof_vel, last_actions
        )
        obs = np.clip(obs, -pm.clipping["observations"], pm.clipping["observations"])
        return obs, base_ang_vel, projected_gravity, legs, dof_pos, dof_vel

    obs, base_ang_vel, projected_gravity, legs, dof_pos, dof_vel = read_state()
    obs_history = np.tile(obs, pm.network["obs_history_length"])

    policy_dt = pm.control_timing["sim_dt"] * pm.control_timing["decimation"]
    n_policy_steps = int(args.seconds / policy_dt)

    # Write this trace to its own named sub-run so multiple collections stay
    # distinguishable; the name carries the date-time and the command values.
    run_dir = os.path.join(args.logdir, build_run_name(args))
    writer = SummaryWriter(log_dir=run_dir)
    print(f"Collecting {args.seconds:.0f}s ({n_policy_steps} steps) -> {run_dir} "
          f"(vx={args.vx}, wz={args.wz}, height={args.height})")

    for step in range(n_policy_steps):
        action = policy.act(obs, obs_history)
        action = np.clip(action, -pm.clipping["actions"], pm.clipping["actions"])

        # Log the state that produced this action and the action itself, so the
        # step index lines up state[k] -> action[k] just like the live loop.
        log_state(writer, step, base_ang_vel, projected_gravity, commands, legs, dof_vel, dof_pos)
        log_actions(writer, step, action)

        # Same torque applied for DECIMATION physics steps (mirrors play_mujoco).
        for _ in range(pm.control_timing["decimation"]):
            dof_pos = data.qpos[pm.QPOS_JOINT_START:].copy()
            dof_vel = data.qvel[pm.QVEL_JOINT_START:].copy()
            legs = ctrl.leg_states(dof_pos, dof_vel)
            data.ctrl[:] = ctrl.compute_torques(action, legs, dof_vel)
            mujoco.mj_step(model, data)

        last_actions = action
        obs, base_ang_vel, projected_gravity, legs, dof_pos, dof_vel = read_state()
        obs_history = np.concatenate([obs_history[pm.network["num_obs"]:], obs])

    writer.flush()
    writer.close()
    print(f"Done. wrote TensorBoard scalars for {n_policy_steps} steps to {run_dir}")


if __name__ == "__main__":
    main()
